version: '3'

services:
  db:
    image: 'postgres:11.4'
    container_name: 'suika-db'
    ports: ['5432:5432']
    environment:
      - POSTGRES_PASSWORD=hunter2
    volumes:
      - suika-data:/var/lib/postgresql/data

volumes:
  suika-data:
